### PR TITLE
Chef Tests

### PR DESCRIPTION
**Pull request by Skuxa**
Implement #76, retrying after previous attempts.

### CODE REVIEW

**Comment by Skuxa** [comment]
I named this commit poorly, only removed in chefTests

**Comment by dislocated-su** [comment]
> I named this commit poorly, only removed in chefTests due to CI not appreciating it's existence. It'd be nice if someone could figure out why that is but it doesn't really matter tbh.

`popIngredient()` is renamed to `popFood() in #73. This is to allow for any type of food to be removed from the chef stack.

**Review by dislocated-su — APPROVED** [review]
Well done

**Comment by Skuxa** [comment]
Thanks, I'll probably add that in a later commit to cover the function.

**Pull request merged**
